name: Test

on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Get dependencies
      run: |
        go mod tidy
        go install github.com/tenntenn/testtime/cmd/testtime@latest

    - name: Run test
      run: go test -race -overlay=$(testtime) -shuffle on -count 1 ./...

